# Configuration for Acrobot environment
# Extends the base config with Acrobot specific settings

defaults:
  - config # inherit from default config

# Override specific values
env_id: Acrobot-v1
total_timesteps: 600000
learning_rate: 5e-4
buffer_size: 20000
gamma: 0.99
exploration_fraction: 0.4