# Configuration for Mountain Car environment
# Extends the base config with Mountain Car specific settings

defaults:
  - config # inherit from default config

# Override specific values
env_id: MountainCar-v0
total_timesteps: 1000000
learning_rate: 1e-3
buffer_size: 50000
gamma: 0.98
batch_size: 256
exploration_fraction: 0.3