# Exploration parameters sweep configuration

defaults:
  - /config # inherit from base config

# Fixed parameters for this sweep
env_id: CartPole-v1
total_timesteps: 500000

# Sweep parameters
hydra:
  sweeper:
    params:
      start_e: 0.8,1.0
      end_e: 0.01,0.05,0.1
      exploration_fraction: 0.3,0.5,0.7